import type {
  AlertRecord,
  ClinicalReport,
  ModelMetric,
  PatientSummary,
  Profile,
  RagDocument,
  RiskPrediction,
  SystemMetrics,
  VitalSigns,
} from "@/types";

export const mockProfiles: Profile[] = [
  {
    id: "patient-demo-1",
    role: "patient",
    full_name: "Ana Mercedes Perez",
    document_id: "100200300",
    telegram_chat_id: 101010,
    assigned_doctor_id: "doctor-demo-1",
    email: "ana@example.com",
  },
  {
    id: "ips-demo-1",
    role: "ips",
    full_name: "Dra. Laura Suarez",
    document_id: "900100",
    telegram_chat_id: 202020,
    email: "laura@ips-atlantico.co",
  },
  {
    id: "admin-demo-1",
    role: "admin",
    full_name: "Administrador HomecareCCV",
    email: "admin@homecareccv.co",
  },
];

export const mockVitals: VitalSigns[] = [
  {
    id: "vital-10",
    patient_id: "patient-demo-1",
    recorded_at: "2026-05-26T06:00:00-05:00",
    systolic_bp: 138,
    diastolic_bp: 84,
    heart_rate: 76,
    oxygen_saturation: 97,
    glucose: 118,
    pain_score: 1,
    dizziness_score: 0,
    dyspnea_score: 0,
  },
  {
    id: "vital-9",
    patient_id: "patient-demo-1",
    recorded_at: "2026-05-25T18:00:00-05:00",
    systolic_bp: 146,
    diastolic_bp: 88,
    heart_rate: 82,
    oxygen_saturation: 96,
    glucose: 132,
    pain_score: 2,
    dizziness_score: 1,
    dyspnea_score: 1,
  },
  {
    id: "vital-8",
    patient_id: "patient-demo-1",
    recorded_at: "2026-05-25T12:00:00-05:00",
    systolic_bp: 154,
    diastolic_bp: 92,
    heart_rate: 86,
    oxygen_saturation: 95,
    glucose: 165,
    pain_score: 2,
    dizziness_score: 2,
    dyspnea_score: 1,
  },
  {
    id: "vital-7",
    patient_id: "patient-demo-1",
    recorded_at: "2026-05-25T06:00:00-05:00",
    systolic_bp: 161,
    diastolic_bp: 94,
    heart_rate: 89,
    oxygen_saturation: 95,
    glucose: 188,
    pain_score: 3,
    dizziness_score: 2,
    dyspnea_score: 2,
  },
  {
    id: "vital-6",
    patient_id: "patient-demo-1",
    recorded_at: "2026-05-24T18:00:00-05:00",
    systolic_bp: 148,
    diastolic_bp: 86,
    heart_rate: 80,
    oxygen_saturation: 97,
    glucose: 124,
    pain_score: 1,
    dizziness_score: 0,
    dyspnea_score: 0,
  },
];

export const mockPrediction: RiskPrediction = {
  id: "prediction-demo-1",
  patient_id: "patient-demo-1",
  vital_sign_id: "vital-10",
  predicted_at: "2026-05-26T06:01:00-05:00",
  risk_level: "moderate",
  risk_probability: 0.64,
  model_used: "lightgbm",
  top_risk_factors: [
    { feature: "systolic_bp", value: 138, shap: 0.22 },
    { feature: "age", value: 72, shap: 0.18 },
    { feature: "glucose", value: 118, shap: 0.11 },
  ],
  confidence_score: 0.88,
};

export const mockReport: ClinicalReport = {
  id: "report-demo-1",
  patient_id: "patient-demo-1",
  vital_sign_id: "vital-10",
  prediction_id: "prediction-demo-1",
  generated_at: "2026-05-26T06:02:00-05:00",
  interpretation: "Presion arterial en rango de vigilancia, frecuencia cardiaca estable y saturacion conservada.",
  recommendations:
    "Repetir medicion en el siguiente horario, mantener reposo relativo y reportar si aparece dolor toracico, debilidad, dificultad para hablar o ahogo.",
  follow_up_actions: "Continuar monitoreo cada 6 horas y revisar tendencia si la sistolica supera 160 mmHg.",
  rag_sources: [{ title: "MEWS", source: "criterios de deterioro clinico" }],
};

export const mockPatients: PatientSummary[] = [
  {
    id: "patient-demo-1",
    full_name: "Ana Mercedes Perez",
    document_id: "100200300",
    age: 72,
    city: "Soledad",
    department: "Atlantico",
    latest_risk: "moderate",
    latest_probability: 0.64,
    latest_vitals: mockVitals[0],
    trend: ["low", "moderate", "moderate", "high", "moderate"],
    last_report_at: "2026-05-26T06:00:00-05:00",
    assigned_doctor: "Dra. Laura Suarez",
  },
  {
    id: "patient-demo-2",
    full_name: "Rafael Enrique Diaz",
    document_id: "72200100",
    age: 68,
    city: "Barranquilla",
    department: "Atlantico",
    latest_risk: "critical",
    latest_probability: 0.91,
    latest_vitals: { systolic_bp: 186, diastolic_bp: 102, heart_rate: 118, oxygen_saturation: 90, glucose: 242 },
    trend: ["moderate", "high", "high", "critical", "critical"],
    last_report_at: "2026-05-26T05:55:00-05:00",
    assigned_doctor: "Dra. Laura Suarez",
  },
  {
    id: "patient-demo-3",
    full_name: "Marta Cecilia Lopez",
    document_id: "32770100",
    age: 63,
    city: "Malambo",
    department: "Atlantico",
    latest_risk: "high",
    latest_probability: 0.78,
    latest_vitals: { systolic_bp: 168, diastolic_bp: 96, heart_rate: 92, oxygen_saturation: 94, glucose: 205 },
    trend: ["moderate", "moderate", "high", "high", "high"],
    last_report_at: "2026-05-26T05:45:00-05:00",
    assigned_doctor: "Dra. Laura Suarez",
  },
  {
    id: "patient-demo-4",
    full_name: "Jose Armando Vega",
    document_id: "80033000",
    age: 59,
    city: "Puerto Colombia",
    department: "Atlantico",
    latest_risk: "low",
    latest_probability: 0.23,
    latest_vitals: { systolic_bp: 124, diastolic_bp: 78, heart_rate: 72, oxygen_saturation: 98, glucose: 104 },
    trend: ["low", "low", "low", "moderate", "low"],
    last_report_at: "2026-05-26T04:10:00-05:00",
    assigned_doctor: "Dra. Laura Suarez",
  },
];

export const mockAlerts: AlertRecord[] = [
  {
    id: "alert-demo-1",
    patient_id: "patient-demo-2",
    patient_name: "Rafael Enrique Diaz",
    created_at: "2026-05-26T05:56:00-05:00",
    risk_level: "critical",
    message: "Presion sistolica critica y saturacion baja. Se notifico al equipo IPS.",
    acknowledged: false,
    sent_to_patient: true,
    sent_to_doctor: true,
    email_sent: true,
    telegram_sent: true,
  },
  {
    id: "alert-demo-2",
    patient_id: "patient-demo-3",
    patient_name: "Marta Cecilia Lopez",
    created_at: "2026-05-26T05:47:00-05:00",
    risk_level: "high",
    message: "Riesgo alto por presion elevada persistente y glucosa sobre 200 mg/dL.",
    acknowledged: false,
    sent_to_patient: true,
    sent_to_doctor: true,
    email_sent: true,
    telegram_sent: true,
  },
  {
    id: "alert-demo-3",
    patient_id: "patient-demo-1",
    patient_name: "Ana Mercedes Perez",
    created_at: "2026-05-25T12:01:00-05:00",
    risk_level: "moderate",
    message: "Seguimiento por tendencia ascendente de presion arterial.",
    acknowledged: true,
    sent_to_patient: false,
    sent_to_doctor: false,
  },
];

export const mockModelMetrics: ModelMetric[] = [
  { model: "lightgbm", status: "trained", train_rows_used: 155912, validation: { f1_macro: 0.987 }, test: { f1_macro: 0.9733 } },
  { model: "xgboost", status: "trained", train_rows_used: 155912, validation: { f1_macro: 0.981 }, test: { f1_macro: 0.9785 } },
  { model: "random_forest", status: "trained", train_rows_used: 155912, validation: { f1_macro: 0.9837 }, test: { f1_macro: 0.9614 } },
  { model: "catboost", status: "trained", train_rows_used: 155912, validation: { f1_macro: 0.9724 }, test: { f1_macro: 0.9772 } },
  { model: "mlp", status: "trained", train_rows_used: 12000, validation: { f1_macro: 0.9092 }, test: { f1_macro: 0.8961 } },
];

export const mockRagDocuments: RagDocument[] = [
  { id: "rag-1", title: "Lineamientos MINSALUD ECV 2022-2026", source: "MINSALUD Colombia", chunk_count: 42, created_at: "2026-05-20" },
  { id: "rag-2", title: "Criterios MEWS", source: "Clinical early warning score", chunk_count: 18, created_at: "2026-05-20" },
  { id: "rag-3", title: "AHA/ASA Stroke Prevention 2024", source: "AHA/ASA", chunk_count: 55, created_at: "2026-05-21" },
];

export const mockSystemMetrics: SystemMetrics = {
  totalPatients: mockPatients.length,
  reportsToday: 18,
  alertsToday: 2,
  criticalAlerts: 1,
};
